apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "tareas" # Cambia esta contraseña
        - name: MYSQL_DATABASE
          value: "tareas"
        - name: MYSQL_USER
          value: "tareas"
        - name: MYSQL_PASSWORD
          value: "tareas"
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
