apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: gustavoquintero/web-image:v2  # Usa el nombre completo de la imagen en Docker Hub
        ports:
        - containerPort: 80

